# Base information
baseURL = "https://marah.dev"
languageCode = "en-gb"
title = "Carlos Marah"
googleAnalytics = ""

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight=2

  [[menu.main]]
  name = "Projects"
  URL = "portfolio"
  weight=3

  [[menu.main]]
  name = "Maths"
  URL = "math"
  weight=4

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight=5


[params]
home = "Home"
description = "Carlos' personal website, mathematician & programmer based in Spain"
author = "Carlos María Rodríguez"

  [params.footer]
  email = "carlos@marah.dev"
  address = "Madrid, ES"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4
